Check API version before using setStatusBarColor()
Window.setStatusBarColor() is available from API version 21
(Lollipop) only.

Since minSdkVersion is set to 16, the app will crash on every
device below Lollipop throwing java.lang.NoSuchMethodError.